# Generated by Django 4.2.6 on 2023-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_alter_image_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
